-- ============================================================
-- SCRIPT 01 — Infrastructure Snowflake pour FinTrack Perf & Scale
-- ============================================================
-- Ce script provisionne :
--   - Base + schémas RAW / STAGING / MARTS_CORE / MARTS_FINANCE / MARTS_ANALYTICS
--   - Warehouses multiples (ingestion, transformation, BI, ad-hoc)
--   - Rôles séparés par usage
--   - Resource monitors avec quotas
--
-- À exécuter avec un rôle disposant d'ACCOUNTADMIN.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- ============================================
-- BASE ET SCHÉMAS
-- ============================================
CREATE DATABASE IF NOT EXISTS FINTRACK_PROD;

CREATE SCHEMA IF NOT EXISTS FINTRACK_PROD.RAW;
CREATE SCHEMA IF NOT EXISTS FINTRACK_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS FINTRACK_PROD.MARTS_CORE;
CREATE SCHEMA IF NOT EXISTS FINTRACK_PROD.MARTS_FINANCE;
CREATE SCHEMA IF NOT EXISTS FINTRACK_PROD.MARTS_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS FINTRACK_PROD.AUDIT;
CREATE SCHEMA IF NOT EXISTS FINTRACK_PROD.SNAPSHOTS;

-- Base de dev (pour les schémas personnels des développeurs)
CREATE DATABASE IF NOT EXISTS FINTRACK_DEV;

-- ============================================
-- RESOURCE MONITORS (contrôle des coûts)
-- ============================================
CREATE RESOURCE MONITOR IF NOT EXISTS RM_FINTRACK_MONTHLY
    WITH CREDIT_QUOTA = 100
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- ============================================
-- WAREHOUSES SPÉCIALISÉS
-- ============================================
-- Ingestion : puissant, réservé aux gros COPY INTO
CREATE WAREHOUSE IF NOT EXISTS WH_INGESTION
    WITH WAREHOUSE_SIZE = 'LARGE'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    SCALING_POLICY = 'STANDARD'
    RESOURCE_MONITOR = RM_FINTRACK_MONTHLY
    COMMENT = 'Chargements bulk depuis stages';

-- Transformation dbt : medium, multicluster pour paralléliser
CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM
    WITH WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = 'STANDARD'
    RESOURCE_MONITOR = RM_FINTRACK_MONTHLY
    COMMENT = 'Exécution des modèles dbt';

-- BI/reporting : small, multicluster élastique
CREATE WAREHOUSE IF NOT EXISTS WH_REPORTING
    WITH WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 5
    SCALING_POLICY = 'ECONOMY'
    RESOURCE_MONITOR = RM_FINTRACK_MONTHLY
    COMMENT = 'Requêtes BI et dashboards';

-- Ad-hoc : xsmall, pour exploration et debug
CREATE WAREHOUSE IF NOT EXISTS WH_ADHOC
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    RESOURCE_MONITOR = RM_FINTRACK_MONTHLY
    COMMENT = 'Ad-hoc, debug, exploration';

-- Dev : xsmall pour développement personnel
CREATE WAREHOUSE IF NOT EXISTS WH_DEV
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    COMMENT = 'Développement local';

-- ============================================
-- RÔLES SÉPARÉS PAR FONCTION
-- ============================================
CREATE ROLE IF NOT EXISTS FINTRACK_INGESTION_ROLE;
CREATE ROLE IF NOT EXISTS FINTRACK_TRANSFORM_ROLE;
CREATE ROLE IF NOT EXISTS FINTRACK_REPORTING_ROLE;
CREATE ROLE IF NOT EXISTS FINTRACK_ADHOC_ROLE;
CREATE ROLE IF NOT EXISTS FINTRACK_DEV_ROLE;

-- Ingestion : accès au RAW en écriture
GRANT USAGE ON DATABASE FINTRACK_PROD TO ROLE FINTRACK_INGESTION_ROLE;
GRANT USAGE ON SCHEMA FINTRACK_PROD.RAW TO ROLE FINTRACK_INGESTION_ROLE;
GRANT ALL ON SCHEMA FINTRACK_PROD.RAW TO ROLE FINTRACK_INGESTION_ROLE;
GRANT USAGE ON WAREHOUSE WH_INGESTION TO ROLE FINTRACK_INGESTION_ROLE;

-- Transform : lecture RAW, écriture STAGING/MARTS
GRANT USAGE ON DATABASE FINTRACK_PROD TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT USAGE ON SCHEMA FINTRACK_PROD.RAW TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FINTRACK_PROD.RAW TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTRACK_PROD.RAW TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT ALL ON SCHEMA FINTRACK_PROD.STAGING TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT ALL ON SCHEMA FINTRACK_PROD.MARTS_CORE TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT ALL ON SCHEMA FINTRACK_PROD.MARTS_FINANCE TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT ALL ON SCHEMA FINTRACK_PROD.MARTS_ANALYTICS TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT ALL ON SCHEMA FINTRACK_PROD.SNAPSHOTS TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT ALL ON SCHEMA FINTRACK_PROD.AUDIT TO ROLE FINTRACK_TRANSFORM_ROLE;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM TO ROLE FINTRACK_TRANSFORM_ROLE;

-- Reporting : lecture seule sur MARTS
GRANT USAGE ON DATABASE FINTRACK_PROD TO ROLE FINTRACK_REPORTING_ROLE;
GRANT USAGE ON SCHEMA FINTRACK_PROD.MARTS_CORE TO ROLE FINTRACK_REPORTING_ROLE;
GRANT USAGE ON SCHEMA FINTRACK_PROD.MARTS_FINANCE TO ROLE FINTRACK_REPORTING_ROLE;
GRANT USAGE ON SCHEMA FINTRACK_PROD.MARTS_ANALYTICS TO ROLE FINTRACK_REPORTING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FINTRACK_PROD.MARTS_CORE TO ROLE FINTRACK_REPORTING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FINTRACK_PROD.MARTS_FINANCE TO ROLE FINTRACK_REPORTING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FINTRACK_PROD.MARTS_ANALYTICS TO ROLE FINTRACK_REPORTING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTRACK_PROD.MARTS_CORE TO ROLE FINTRACK_REPORTING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTRACK_PROD.MARTS_FINANCE TO ROLE FINTRACK_REPORTING_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FINTRACK_PROD.MARTS_ANALYTICS TO ROLE FINTRACK_REPORTING_ROLE;
GRANT USAGE ON WAREHOUSE WH_REPORTING TO ROLE FINTRACK_REPORTING_ROLE;

-- Ad-hoc : lecture seule sur toute la base
GRANT USAGE ON DATABASE FINTRACK_PROD TO ROLE FINTRACK_ADHOC_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FINTRACK_PROD TO ROLE FINTRACK_ADHOC_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE FINTRACK_PROD TO ROLE FINTRACK_ADHOC_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE FINTRACK_PROD TO ROLE FINTRACK_ADHOC_ROLE;
GRANT USAGE ON WAREHOUSE WH_ADHOC TO ROLE FINTRACK_ADHOC_ROLE;

-- Dev : accès complet à la base de dev
GRANT ALL ON DATABASE FINTRACK_DEV TO ROLE FINTRACK_DEV_ROLE;
GRANT USAGE ON DATABASE FINTRACK_PROD TO ROLE FINTRACK_DEV_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FINTRACK_PROD TO ROLE FINTRACK_DEV_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE FINTRACK_PROD TO ROLE FINTRACK_DEV_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE FINTRACK_PROD TO ROLE FINTRACK_DEV_ROLE;
GRANT USAGE ON WAREHOUSE WH_DEV TO ROLE FINTRACK_DEV_ROLE;

-- ============================================
-- ATTRIBUTION AUX UTILISATEURS
-- ============================================
-- À adapter à votre utilisateur :
-- GRANT ROLE FINTRACK_TRANSFORM_ROLE TO USER <votre_utilisateur>;
-- GRANT ROLE FINTRACK_DEV_ROLE TO USER <votre_utilisateur>;
